version: "3.9"
services:
  webserver:
    build: ./nginx
    ports:
      - "8080:8080"
    links:
      - web:web
  # end of ningx web server

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  # end of db

  web:
    # image: kapildtreelabs/se-demo-docker-testing
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000-3010:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
  # enf of web rails application
