default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: p@ssw0rd
  pool: 5

development:
  <<: *default
  database: myapp_development

production:
  <<: *default
  database: myapp_prod

test:
  <<: *default
  database: myapp_test